---
output:
  pdf_document: default
  html_document: default
---

# Conclusion {#conclusion}

Missing data is is an important problem in the field of statistics which will most likely continue to plague data in the next few decades. As an issue for which there is no one-size-fits-all solution designed to effectively remedy it, it is important for practiced statisticians to understand and carefully consider what type of method to use for the situation at hand. In this thesis, we provided an overview regarding the concept of missingness, specifically with censoring, and the ramifications that it can have on statistical analyses. We discussed methods designed to work with left-censored data: substitution, ML estimation, KM, and ROS, which are designed to obtain parameter estimates for left-censored datasets. After our exploration on the theoretical foundations of these methods, we carefully designed a simulation study to investigate our hypothesis the effectiveness of each of our methods would differ when for different proportions, sizes, and underlying distribution for the dataset. We then introduced the problem of coal ash contamination across groundwater wells in the U.S. and introduced the @Kelderman2019's report which contained information regarding the top ten most contaminated coal sites across the U.S. Due to a lack of discussion in @Kelderman2019's report regarding how they accounted for left-censoring in their analysis, we believed that conclusions may have differed if different methods of handling the left-censored data were used. Motivated by this report, we conducted a case study to explore using a baseline method, substitution, and KM to identify our own top ten most contaminated sites, and compared our results to those obtained by @Kelderman2019. 

Even among the many peer-reviewed papers and reports which compared and contrasted several of these methods via. different scopes of field of study, a common shared idea was the impossibility of pinning one method down as being the "best". Even from our own case study, we had trouble implementing the MLE and ROS methods for our water quality data, due to issues such as the percentage of censoring being too high or our data being too highly skewed for the methods to be used. Future work could involve finding a way to account for these issues, perhaps investigating the efficacy of our methods with transformed data, would be a conducive path to follow.

The motivation for our thesis was largely centered on left-censored data, which is commonly found in environmental sciences with water quality datasets. Due to recent innovations in data storage and data provenance in general, data is becoming increasingly easier to access for the general public. As such, it would be expected that many of these datasets will inevitably contain missing data as well. Further investigation and research in technologies and methods to handle missingness will become increasingly important in order to prevent the discarding information by throwing out missing data. 