# Simulation/CS Appendix

The second appendix, Appendix B, contains all necessary code required to run the simulation study and for our case study.

## Simulation Study

### Libraries

```{r app_libraries, ref.label="libraries", echo=TRUE, eval=FALSE}
```

### Generating Data

```{r app_gd, ref.label=c("generateLN", "generateEXP", "generateW"), echo=TRUE, eval=FALSE}
```

### Setup

```{r app_setup, ref.label= "setup", echo=TRUE, eval=FALSE}
```

### Lognormal

```{r app_ln, ref.label= "lognormal", echo=TRUE, eval=FALSE}
```

### Exponential

```{r app_exp, ref.label= "exponential", echo=TRUE, eval=FALSE}
```

### Weibull

```{r app_w, ref.label= "weibull", echo=TRUE, eval=FALSE}
```

## Case Study

### Preliminary

```{r app_prelim, ref.label= "prelim", echo=TRUE, eval=FALSE}
```

### Standardization of Units

```{r app_standardize, ref.label= "standardize", echo=TRUE, eval=FALSE}
```

### Baseline/Control

```{r app_baseline, ref.label= "baseline", echo=TRUE, eval=FALSE}
```

### Substitution

```{r app_substitution, ref.label= "substitution", echo=TRUE, eval=FALSE}
```

### KM

```{r app_km, ref.label= "km", echo=TRUE, eval=FALSE}
```

### MLE (excluded)

```{r app_mle, ref.label= "mle", echo=TRUE, eval=FALSE}
```

### ROS (excluded)

```{r app_ros, ref.label= "ros", echo=TRUE, eval=FALSE}
```


