---
title: "Indentifying Contaminated Wells"
author: "Tony Ni"
date: "7/26/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries

```{r}
library(tidyverse)
```

## Reading in Data

```{r}
df <- read_csv("data/long_illinois.csv") #read in data
```

## Introduction

We are seeking to identify the contaminated wells manually (with filters).

## More Wrangling

```{r}
#creating vector of contaminants
contaminant <- unique(df$contaminant)

#creating vector of threshold values for each contaminant
threshold <- c(6/1000, 10/1000, 2, 4/1000, 3, 5/1000, NA, NA, 100/1000, 
               6/1000, NA, 15/1000, 40/1000, 2/1000, 40/1000, NA, 5, 
               50/1000, 500, 2/1000, NA)

contam_t <- cbind(contaminant, threshold) %>%
  na.omit()
```

```{r}
#creating function to obtain all observations with values above threshold
#for upgradient wells

getOverThreshold <- function(df){
  datalist = list()
  for(i in 1:nrow(contam_t)){ #for each contaminant i
    df1 <- filter(df, gradient == "Upgradient")
    df2 <- filter(df1, contaminant == contam_t[i])
    data <- filter(df2, concentration > contam_t[nrow(contam_t) + i])
    datalist[[i]] <- data
  }
  toReturn <- do.call(rbind, datalist)
  
  return(toReturn)
}
```

```{r}
#using the function on data
overthreshold_df <- getOverThreshold(df) #df with all observations over threshold value
glimpse(overthreshold_df)
```